### ISSUE TITLE
Could you help me to use this plugin with pytest filter (pytest -mark)？

### ISSUE THREAD

**Issue by zengzizuan** [FrancescElies/pytest-azure-devops#1]
Hi, Elies
  I saw the excellent plugin you have published and download it in my pipeline.
  I just want to ask one question is : can it distribute test case in range of test case which after pytest collected and use -mark filter, it means assuming that collected 9 items / 5 deselected / 4 selected, and the rule will be：
          This is agent nr. 1 out of 2 and will run 2 out of 4 (the number is test cases selected by pytest -mark)
          This is agent nr. 2 out of 2 and will run 2 out of 4
But not now：
          This is agent nr. 1 out of 2 and will run 5 out of 9(the number is all test cases collected by pytest)
          This is agent nr. 2 out of 2 and will run 4 out of 9
I didn‘t use tox, I'm not sure if the problem is here, is it necessary?
Thanks in advance!
Best Regards,
Kerria

**Comment by FrancescElies** [comment]
@zengzizuan the fastest way to see this implemented is to provide a pr, I'll be happy to merge it if you do so.
